modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="confections"
version="1.0.0"
displayName="Confections Galore"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ldeze, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.confections]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.confections]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.confections]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

